apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator # Name of the deployment
  namespace: data # Name of the namespace
  labels:
    app: data-generator # Name of your application
spec:
  selector:
    matchLabels:
      app: data-generator # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: data-generator # Name of your application
    spec:
      containers:
      - name: data-generator
        build:
          artifacts:
            - image: data-generator
              context: ../../../data_generator
              docker:
                dockerfile: Dockerfile
        image: data-generator
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: RABBITMQ_HOST
          value: production-rabbitmqcluster.services.svc.cluster.local
        - name: REDIS_HOST
          value: redis
