apiVersion: apps/v1
kind: Deployment
metadata:
  name: web # Name of the deployment
  namespace: data # Name of the namespace
  labels:
    app: web # Name of your application
spec:
  selector:
    matchLabels:
      app: web # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: web # Name of your application
    spec:
      containers:
      - name: web
        image: 10.108.89.79:5000/web:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
