apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: services
spec:
  type: ClusterIP
  externalIPs:
    - 10.10.1.50
  selector:
    app: registry
  ports:
  - port: 5000
    protocol: TCP
    name: registry
