apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend # Name of the deployment
  namespace: data # Name of the namespace
  labels:
    app: backend # Name of your application
spec:
  selector:
    matchLabels:
      app: backend # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: backend # Name of your application
    spec:
      containers:
      - name: backend
        image: 10.108.89.79:5000/backend:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq.services.svc.cluster.local
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-es-http.services.svc.cluster.local
